// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: queries.sql

package db

import (
	"context"
)

const findRotaByID = `-- name: FindRotaByID :one
SELECT rotas.id, rotas.team_id, rotas.channel_id, rotas.name, rotas.metadata, rotas.created_at, rotas.updated_at
FROM ROTAS
WHERE ID = $1
`

func (q *Queries) FindRotaByID(ctx context.Context, id string) (Rota, error) {
	row := q.db.QueryRow(ctx, findRotaByID, id)
	var i Rota
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ChannelID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRotasByChannel = `-- name: ListRotasByChannel :many
SELECT rotas.id, rotas.team_id, rotas.channel_id, rotas.name, rotas.metadata, rotas.created_at, rotas.updated_at
FROM ROTAS
WHERE ROTAS.CHANNEL_ID = $1
  AND ROTAS.TEAM_ID = $2
`

type ListRotasByChannelParams struct {
	ChannelID string `json:"channel_id"`
	TeamID    string `json:"team_id"`
}

func (q *Queries) ListRotasByChannel(ctx context.Context, arg ListRotasByChannelParams) ([]Rota, error) {
	rows, err := q.db.Query(ctx, listRotasByChannel, arg.ChannelID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rota{}
	for rows.Next() {
		var i Rota
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ChannelID,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDsByRotaID = `-- name: ListUserIDsByRotaID :many
SELECT MEMBERS.USER_ID
FROM MEMBERS
WHERE MEMBERS.ROTA_ID = $1
`

func (q *Queries) ListUserIDsByRotaID(ctx context.Context, rotaID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserIDsByRotaID, rotaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMember = `-- name: deleteMember :exec
DELETE FROM MEMBERS WHERE USER_ID = $1
`

func (q *Queries) deleteMember(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteMember, userID)
	return err
}

const saveMember = `-- name: saveMember :one
INSERT INTO MEMBERS (ROTA_ID, USER_ID, METADATA)
VALUES ($1, $2, $3) RETURNING ID
`

type saveMemberParams struct {
	RotaID   string         `json:"rota_id"`
	UserID   string         `json:"user_id"`
	Metadata MemberMetadata `json:"metadata"`
}

func (q *Queries) saveMember(ctx context.Context, arg saveMemberParams) (string, error) {
	row := q.db.QueryRow(ctx, saveMember, arg.RotaID, arg.UserID, arg.Metadata)
	var id string
	err := row.Scan(&id)
	return id, err
}

const saveRota = `-- name: saveRota :one
INSERT INTO ROTAS (TEAM_ID, CHANNEL_ID, NAME, METADATA)
VALUES ($1, $2, $3, $4) RETURNING ID
`

type saveRotaParams struct {
	TeamID    string       `json:"team_id"`
	ChannelID string       `json:"channel_id"`
	Name      string       `json:"name"`
	Metadata  RotaMetadata `json:"metadata"`
}

func (q *Queries) saveRota(ctx context.Context, arg saveRotaParams) (string, error) {
	row := q.db.QueryRow(ctx, saveRota,
		arg.TeamID,
		arg.ChannelID,
		arg.Name,
		arg.Metadata,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateRota = `-- name: updateRota :one
UPDATE ROTAS
SET NAME     = $1,
    METADATA = $2
WHERE ID = $3 RETURNING ID
`

type updateRotaParams struct {
	Name     string       `json:"name"`
	Metadata RotaMetadata `json:"metadata"`
	ID       string       `json:"id"`
}

func (q *Queries) updateRota(ctx context.Context, arg updateRotaParams) (string, error) {
	row := q.db.QueryRow(ctx, updateRota, arg.Name, arg.Metadata, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}
