// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: rotas.sql

package db

import (
	"context"
)

const listRotas = `-- name: ListRotas :many
SELECT id, organization_id, channel_id, name, type, created_at, updated_at from ROTAS
`

func (q *Queries) ListRotas(ctx context.Context) ([]Rota, error) {
	rows, err := q.db.Query(ctx, listRotas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rota
	for rows.Next() {
		var i Rota
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ChannelID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
