CREATE TABLE ROTAS
(
    ID         TEXT PRIMARY KEY   DEFAULT ('RT' || generate_uid(14)),
    TEAM_ID    TEXT      NOT NULL,
    CHANNEL_ID TEXT      NOT NULL,
    NAME       TEXT      NOT NULL,
    METADATA   JSONB     NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_unique_rota_within_team_and_channel ON ROTAS (NAME, CHANNEL_ID, TEAM_ID);
