swagger: "2.0"
info:
    title: Rotabot - Making rotas dead simple
    description: A service for working with rotas across multiples tools i.e Slack, Teams, etc
    version: ""
host: localhost:8080
consumes:
    - application/json
    - application/x-www-form-urlencoded
produces:
    - application/json
paths:
    /slack/commands:
        post:
            tags:
                - Slack
            summary: Commands Slack
            operationId: Slack#Commands
            parameters:
                - name: X-Slack-Signature
                  in: header
                  required: true
                  type: string
                - name: X-Slack-Request-Timestamp
                  in: header
                  required: true
                  type: integer
                  format: int64
                - name: CommandsRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/SlackCommandsRequestBody'
                    required:
                        - token
                        - command
                        - trigger_id
                        - user_id
                        - team_id
                        - channel_id
            responses:
                "200":
                    description: OK response.
            schemes:
                - http
    /slack/events:
        post:
            tags:
                - Slack
            summary: Events Slack
            operationId: Slack#Events
            parameters:
                - name: X-Slack-Signature
                  in: header
                  required: true
                  type: string
                - name: X-Slack-Request-Timestamp
                  in: header
                  required: true
                  type: integer
                  format: int64
                - name: EventsRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/SlackEventsRequestBody'
                    required:
                        - token
                        - team_id
                        - type
                        - api_app_id
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/SlackEventsResponseBody'
            schemes:
                - http
    /slack/message_actions:
        post:
            tags:
                - Slack
            summary: MessageActions Slack
            operationId: Slack#MessageActions
            parameters:
                - name: X-Slack-Signature
                  in: header
                  required: true
                  type: string
                - name: X-Slack-Request-Timestamp
                  in: header
                  required: true
                  type: integer
                  format: int64
                - name: MessageActionsRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/SlackMessageActionsRequestBody'
                    required:
                        - payload
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/SlackMessageActionsResponseBody'
            schemes:
                - http
definitions:
    SlackCommandsRequestBody:
        title: SlackCommandsRequestBody
        type: object
        properties:
            api_app_id:
                type: string
                example: Repudiandae placeat hic dignissimos debitis nisi quidem.
            channel_id:
                type: string
                example: Quas aperiam nihil.
            channel_name:
                type: string
                example: Molestias at quasi.
            command:
                type: string
                example: Expedita fuga sed rerum eum.
            enterprise_id:
                type: string
                example: Sapiente iure ducimus eveniet aliquam.
            enterprise_name:
                type: string
                example: Magnam voluptatem molestiae rerum.
            is_enterprise_install:
                type: boolean
                example: false
            response_url:
                type: string
                example: Aspernatur voluptas.
            team_domain:
                type: string
                example: Exercitationem nihil voluptates facere eum rerum.
            team_id:
                type: string
                example: Eius quos qui debitis modi quo voluptates.
            text:
                type: string
                example: Exercitationem officia eum.
            token:
                type: string
                example: Dolor natus aut non.
            trigger_id:
                type: string
                example: Numquam in rerum id eos.
            user_id:
                type: string
                example: Aliquid neque quia.
            user_name:
                type: string
                example: Eum voluptatem rem iusto.
        example:
            api_app_id: Debitis culpa in iste quidem.
            channel_id: Velit ipsam.
            channel_name: Eius asperiores dolores nobis.
            command: Qui dolorem sint est iure quia.
            enterprise_id: In et alias velit magni.
            enterprise_name: Nobis et cupiditate nostrum ipsum.
            is_enterprise_install: true
            response_url: Recusandae qui explicabo aspernatur quas et et.
            team_domain: Quis minima sint doloribus earum odit.
            team_id: Iste voluptatem vel magnam laborum.
            text: Ut at voluptate odit minus provident.
            token: Veniam ducimus delectus qui distinctio rem.
            trigger_id: Et earum voluptatem quas voluptas sapiente.
            user_id: Dolor officia minima est autem error.
            user_name: Necessitatibus consectetur est.
        required:
            - token
            - command
            - trigger_id
            - user_id
            - team_id
            - channel_id
    SlackEventsRequestBody:
        title: SlackEventsRequestBody
        type: object
        properties:
            api_app_id:
                type: string
                example: Nesciunt vitae.
            challenge:
                type: string
                example: Quod molestias aut perferendis deleniti.
            event:
                type: object
                properties:
                    type:
                        type: string
                        example: Cum distinctio.
                description: The actual event information
                example:
                    type: Nesciunt corporis vel ipsam vero.
            team_id:
                type: string
                example: Assumenda eos.
            token:
                type: string
                example: Sed laborum quia facere.
            type:
                type: string
                example: Eos suscipit harum laborum dolorem deserunt et.
        example:
            api_app_id: Nam similique vero sequi ut voluptas laborum.
            challenge: Optio corporis sunt ratione et.
            event:
                type: Est voluptas qui dolor libero voluptate voluptate.
            team_id: Est eaque inventore nam quaerat omnis et.
            token: Adipisci sequi.
            type: Eos cupiditate fuga quo officiis unde quisquam.
        required:
            - token
            - team_id
            - type
            - api_app_id
    SlackEventsResponseBody:
        title: SlackEventsResponseBody
        type: object
        properties:
            challenge:
                type: string
                example: randomstring
        example:
            challenge: randomstring
    SlackMessageActionsRequestBody:
        title: SlackMessageActionsRequestBody
        type: object
        properties:
            payload:
                type: string
                example:
                    - 65
                    - 110
                    - 105
                    - 109
                    - 105
                    - 32
                    - 99
                    - 111
                    - 110
                    - 115
                    - 101
                    - 113
                    - 117
                    - 97
                    - 116
                    - 117
                    - 114
                    - 32
                    - 105
                    - 115
                    - 116
                    - 101
                    - 46
                format: byte
        example:
            payload:
                - 77
                - 105
                - 110
                - 105
                - 109
                - 97
                - 32
                - 112
                - 111
                - 115
                - 115
                - 105
                - 109
                - 117
                - 115
                - 32
                - 114
                - 101
                - 114
                - 117
                - 109
                - 32
                - 101
                - 115
                - 116
                - 32
                - 113
                - 117
                - 105
                - 32
                - 105
                - 112
                - 115
                - 117
                - 109
                - 46
        required:
            - payload
    SlackMessageActionsResponseBody:
        title: SlackMessageActionsResponseBody
        type: object
        properties:
            errors:
                type: object
                example:
                    foo: bar
                additionalProperties:
                    type: string
                    example: Saepe non praesentium ea voluptas maxime natus.
            response_action:
                type: string
                example: errors
            view:
                type: string
                example: Debitis porro et perferendis itaque architecto.
                format: binary
        example:
            errors:
                foo: bar
            response_action: errors
            view: Cumque aliquid omnis.
