-- name: FindRotaByID :one
SELECT ROTAS.*
FROM ROTAS
WHERE ID = $1;

-- name: ListRotasByChannel :many
SELECT ROTAS.*
FROM ROTAS
WHERE ROTAS.CHANNEL_ID = $1
  AND ROTAS.TEAM_ID = $2;

-- name: saveRota :one
INSERT INTO ROTAS (TEAM_ID, CHANNEL_ID, NAME, METADATA)
VALUES ($1, $2, $3, $4) RETURNING ID;

-- name: updateRota :one
UPDATE ROTAS
SET NAME     = $1,
    METADATA = $2
WHERE ID = $3 RETURNING ID;

-- name: saveMember :one
INSERT INTO MEMBERS (ROTA_ID, USER_ID, METADATA)
VALUES ($1, $2, $3) RETURNING ID;

-- name: deleteMember :exec
DELETE FROM MEMBERS WHERE USER_ID = $1;

-- name: ListUserIDsByRotaID :many
SELECT MEMBERS.USER_ID
FROM MEMBERS
WHERE MEMBERS.ROTA_ID = $1;