name: build
permissions: {} # no need any permissions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 10 * * 1' # run "At 10:00 on Monday"
  workflow_call:
jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        go: ['stable']
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code
      - name: Go Tidy
        run: go mod tidy && git diff --exit-code
      - name: Go Vet
        run: go vet ./...
      - name: Go Download
        run: go mod download
      - name: Make Install
        run: make install
      - name: Go Mod Verify
        run: go mod verify
      - name: Generate
        # Running go mod tidy because goa's dependency will generate undesired changes
        run: make generate && go mod tidy && git diff --exit-code
      - name: Go Build
        run: make build
      - name: Go Test
        run: make test
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        continue-on-error: true
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./cover.profile
          fail_ci_if_error: false
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: |
            report.xml
        if: always()
