name: lint
permissions: {} # no need any permissions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint
        uses: golangci/golangci-lint-action@v3.6.0
        with:
          version: latest
          args: --timeout 5m
