name: sqlc
permissions: {} # no need any permissions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
jobs:
  run:
    name: Sqlc
    runs-on: ubuntu-latest
    services:
      postgres:
        image: "postgres:15"
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    timeout-minutes: 5
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup-sqlc
        uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: '1.20.0'
      - name: Run db migrations
        run: |
          make migrations/up DB_DSN=postgres:postgres@localhost:5432/postgres?sslmode=disable
      - run: sqlc diff
      - run: sqlc vet
